### ISSUE TITLE
Universe of discourse?

### ISSUE THREAD

**Issue by jtlz2** [konstantint/matplotlib-venn#32]
Is there an in-built method for plotting a box, symbol and number for the universe of discourse, and if not could you add one?

**Comment by jtlz2** [comment]
Sorry, saw the earlier issue on this....

**Comment by konstantint** [comment]
You can always just add any necessary `Text` patches as you see fit;
```
venn3([{1,2,3}, {2,3}, {3,5}])
top, bottom = plt.gca().get_xlim()[0], plt.gca().get_ylim()[0]
plt.annotate("Universe", (top, bottom));
```

This takes just a couple of extra lines, and I would be reluctant to add this to the library because there may be variations in how one may want to position the additional text. I'm not sure that littering the library with these options is meaningful.

In case there are good counterarguments or if this issue will get more attention or requests, I'm happy to reconsider.
