### ISSUE TITLE
there's space at 3 intersections

### ISSUE THREAD

**Issue by Coaxecva** [konstantint/matplotlib-venn#40]
Hi Konstantin,

I tried to plot venn3: 
```python
plot_venn_3_groups([3*10**6, 3*10**6, 2*10**4, 4*10**6, 3*10**5, 2*10**4, 4*10**3])
```
and it happened that the middle intersection between 3 sets has a space (4000). I think it is because of the high different ratios between sets. Can you help me fix this?

![test](https://user-images.githubusercontent.com/6088844/45791533-aadf4f80-bc4f-11e8-992f-7fb425030c08.png)

Thanks!
Quang

**Comment by konstantint** [comment]
The default circle layout algorithm is made so that circle pairwise intersection areas are "to scale". The diagram does not have sufficient freedom of parameters to also guarantee the appropriate scale of the central part as well, hence in various pathological cases you may find yourself in the situation like the one above.

The only way to overcome it at the moment is to manually tune the central part's area to be larger than it "wants" to be according to your data. There is a utility function `venn3_unweighted` which lets you do it:

```from matplotlib_venn import venn3, venn3_unweighted
venn3_unweighted([3*10**6, 3*10**6, 2*10**4, 4*10**6, 3*10**5, 2*10**4, 4*10**3], 
                subset_areas=[3*10**6, 3*10**6, 2*10**4, 4*10**6, 3*10**5, 2*10**4, 4*10**5])
```

Here the first parameter is only specifying the numbers shown on the circles, and if you do not 
specify `subset_areas` you will get an "unweighted" diagram.
The `subset_areas`, however, lets you specify custom areas and, as you see, providing the same numbers except for the increased last number (which corresponds to the "central area") solves the problem.

There is a dangling task here for developing other layout methods besides the available one, but so far I've never found the time for it and neither does there seem to be a pressing demand for it anyway.

**Comment by Coaxecva** [comment]
Thanks! I fixed the graph with ```venn3_unweighted``:
![test](https://user-images.githubusercontent.com/6088844/45837997-44514480-bcd6-11e8-8a6a-783c6453ca6a.png)
